### ISSUE TITLE
[SIMD] investigate wasm simd implementation

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#332] opened 2020-05-25 07:02 UTC
@lionkunonly , please ramp up wasm simd development by doing following tasks:

- [x] build opencv.js with wasm simd support
- [x] run unit tests of wasm simd intrinsics
- [x] run perf tests of wasm simd and replicate the perf issue of cvtColor and resize kernels

If you meet any issues, please let us know. Thanks!

**Comment by huningxin** [comment] 2020-05-25 07:48
build instruction: https://docs.opencv.org/4.3.0/d4/da1/tutorial_js_setup.html

**Comment by huningxin** [comment] 2020-05-25 07:55
Some references:

OpenCV Universal intrinsics: https://docs.opencv.org/3.4/df/d91/group__core__hal__intrin.html

2019  OpenCV.js WASM SIMD: 
https://gist.github.com/Wenzhao-Xiang/8636e239c20e0eda839833f9d363828e
https://github.com/opencv/opencv/pull/15371/files

WASM intrinsics hal:
https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/hal/intrin_wasm.hpp

WASM SIMD128 :
https://github.com/llvm/llvm-project/blob/master/clang/lib/Headers/wasm_simd128.h
https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md

**Comment by lionkunonly** [comment] 2020-05-28 05:13
Hi, Ningxin. I have built the build opencv.js with wasm simd support. But when I try to use `node.js` (version 14.3.0) to run the js for unit tests of wasm simd intrinsic, it failed. The error log is:
```
TypeError: cv.test_hal_intrin_all is not a function
    at Object.<anonymous> (/home/kunliang/GSoC2020/opencv/build_js/bin/test.js:2:11)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
``` 
And in the Opencv.js build, it prints the log like it:
```
-- OpenCV: system-specific configuration file is not found: 'Emscripten'
-- Looking for ccache - not found
``` 
I have installed the emsripten and test it successfully. I do not know why these logs are printed. Is the reason that causes my problem?

My test js:
```
var cv = require('./opencv');
cv.test_hal_intrin_all()
```

The system is Ubuntu 16.04.  The version of Node.js is 14.3.0. And I have appended `--build_wasm_intrin_test` option for building. Do you meet the problem before?

**Comment by huningxin** [comment] 2020-05-28 07:56
Are you able to run browser tests as "Manually in your browser" of https://docs.opencv.org/master/d4/da1/tutorial_js_setup.html?

**Comment by lionkunonly** [comment] 2020-06-01 15:28
> Are you able to run browser tests as "Manually in your browser" of https://docs.opencv.org/master/d4/da1/tutorial_js_setup.html?

Sorry for the late reply. Due to problems on my environment,  I have to test it in these days. 
I have tried to run browser tests as "Manually in your browser". The result was that it failed.
The following is the screenshot.

![Manully test](https://user-images.githubusercontent.com/26929797/83423891-30278980-a45e-11ea-9743-89df78b2887b.png)

I also tried to build the wasm version of OpenCV.js. And it reports error, too. The error is :
```
Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #62 failed: i64x2.splat[0] expected type i64, found i32.const of type i32 @+42939) at Error
    at jsStackTrace (file:///home/kunliang/GSoC2020/opencv/build_js/bin/opencv.js:31:9643286)
    at stackTrace (file:///home/kunliang/GSoC2020/opencv/build_js/bin/opencv.js:31:9643454)
    at abort (file:///home/kunliang/GSoC2020/opencv/build_js/bin/opencv.js:31:33953)
    at file:///home/kunliang/GSoC2020/opencv/build_js/bin/opencv.js:31:9620290
    at abort (file:///home/kunliang/GSoC2020/opencv/build_js/bin/opencv.js:31:33984)
    at file:///home/kunliang/GSoC2020/opencv/build_js/bin/opencv.js:31:9620290
```

It seems like the problem with the function `splat`.  I have discussed with Zhiming, but both of we can not find out the reason and can not find some suggestion by searching in google. Do you ever meet these problems?

**Comment by huningxin** [comment] 2020-06-02 00:48
Thanks for the following up. What are the versions of your OpenCV (commit) and emscripten (version)?

**Comment by lionkunonly** [comment] 2020-06-02 02:18
emscripten(version):
```
kunliang@KunLiang:~/GSoC2020/opencv$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.16
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 3774bcf9f84520a8c35bf765d9a528040d68a14b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/kunliang/GSoC2020/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)

```

OpenCV(commit):
```
commit 7f453ade
```

**Comment by huningxin** [comment] 2020-06-02 07:07
I can reproduce the unit test issue and simd issue with emscripten 1.39.16. Let's investigate the root cause. BTW, @akineeic , which is the last version of emscripten you built opencv.js / simd successfully recently?

**Comment by akineeic** [comment] 2020-06-02 07:38
> which is the last version of emscripten you built opencv.js / simd successfully recently?

I build with 1.39.1 serveral days ago and send to @lionkunonly to test with no error, maybe can try to return to previous version.

**Comment by huningxin** [comment] 2020-06-02 08:04
I tested with 1.39.1, the tests can run with some errors. My build command
```shell script
$ python platforms/js/build_js.py build_wasm_1.39.1 --build_wasm --build_test --simd \
   --build_wasm_intrin_test
```

The tests.html result is "Total: 562 Failed: 5 Passed: 557". And there are 3 failed cases for `cv.test_hal_intrin_float32()`.

**Comment by huningxin** [comment] 2020-06-02 08:46
The SIMD issue of 1.39.16 may be related to this one: https://github.com/WebAssembly/simd/issues/216. I'll do more investigations.

**Comment by lionkunonly** [comment] 2020-06-03 01:02
> I tested with 1.39.1, the tests can run with some errors. My build command
> 
> ```shell
> $ python platforms/js/build_js.py build_wasm_1.39.1 --build_wasm --build_test --simd \
>    --build_wasm_intrin_test
> ```
> 
> The tests.html result is "Total: 562 Failed: 5 Passed: 557". And there are 3 failed cases for `cv.test_hal_intrin_float32()`.

Hi, Ningxin. I have tested with 1.39.1, too.But the result of test.html is 'Total: 562 Failed: 0 Passed: 562'. There is no error. And I can build the opencv.js that support the functions --  `test_hal_intrin_all()` and others.

**Comment by huningxin** [comment] 2020-06-03 07:32
> But the result of test.html is 'Total: 562 Failed: 0 Passed: 562'. There is no error.

The errors are only for simd build. Did you try simd build?

**Comment by huningxin** [comment] 2020-06-03 07:35
The SIMD issue of emscripten 1.39.16 is fixed by [Chrome dev version](https://www.google.com/chrome/dev/). For me, I can run all test cases of tests.html successfully on Chrome 85.0.4158.4.

@lionkunonly , please help verify that on your side.

**Comment by huningxin** [comment] 2020-06-03 08:15
> I have tried to run browser tests as "Manually in your browser". The result was that it failed.
> The following is the screenshot.

This would be caused by [promise based module](https://github.com/emscripten-core/emscripten/pull/10697) introduced in emscripten 1.39.16.

**Comment by huningxin** [comment] 2020-06-03 08:20
I have a temporary solution as https://github.com/huningxin/opencv/commit/daa62e65196d6af694ac55291a62ff4b73d0dc04, please help verify whether it works for you. @lionkunonly .

**Comment by lionkunonly** [comment] 2020-06-03 12:28
> I have a temporary solution as [daa62e6](https://github.com/huningxin/opencv/commit/daa62e65196d6af694ac55291a62ff4b73d0dc04), please help verify whether it works for you. @lionkunonly .

Thanks for your help, Ningxin.  I have tested the `daa62e6`. The SIMD issue of emscripten 1.39.16 on Chrome 85.0.4158.4 is fixed on my computer.

**Comment by lionkunonly** [comment] 2020-06-03 14:58
> > But the result of test.html is 'Total: 562 Failed: 0 Passed: 562'. There is no error.
> 
> The errors are only for simd build. Did you try simd build?

In the morning, I can get the result with no error and I think I tired simd build at that time. However, in the evening, I find that I can not reproduce the result.

**Comment by lionkunonly** [comment] 2020-06-04 03:24
Hi, Ningxin. Can the function `cv.onRuntimeInitialized` with the `promise based module` work now?  I find some code in perf test use this callback function to control the workflow, but it seems can not work.

**Comment by lionkunonly** [comment] 2020-06-04 07:58
Hi, Ningxin. Due to the emscripten 1.39.16, the node.js can not run the perf test successfully. So I choose to do perf test on browser. We should modify the perf test files to fit the `promise based module`. Now I have run the perf test successfully. 

But in my experiments, I find there is some changes in test result of  kernel CvtColor and Resize. Here are my results.

chrome dev  85.0.4158.4, emscripten 1.39.16
| kernel    |    Parameter   |     WASM(scalar) (ms)   |      WASM(simd) (ms) |
| ------------- | ------------- |  ----------- | -----------|
| CvtColor  |   (1920x1080, COLOR_YUV2BGR) |  18.44 |  10.19|
| CvtColor  |    (1920x1080, COLOR_BGR2YUV) |  19.89 | 12.13|
| Resize     |   (CV_8UC4,1280x720,640x480) | 16.33 | 4.18 |

In my experiments, the WASM SIMD can improve the performance of WASM scalar version, which is different with the result in GSoC 2019. The WASM(scalar) is built with command `python ./platforms/js/build_js.py build_wasm --build_test --build_wasm --build_perf`. The WASM(SIMD) is built with command `python ./platforms/js/build_js.py build_js --build_test --build_wasm --simd --build_perf `.

Could you test on your environment to verify it? I am not sure about my results but I can not find wrong.

**Comment by huningxin** [comment] 2020-06-08 03:09
> We should modify the perf test files to fit the `promise based module`.

@lionkunonly , please send a PR that includes your fix for unit tests and perf test files for emscripten 1.39.16. Please send the PR to https://github.com/huningxin/opencv/tree/gsoc_2020_simd

**Comment by lionkunonly** [comment] 2020-06-08 13:58
My configuration is **Ubuntu 16.04, Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz, chrome dev 85.0.4158.4, and emscripten 1.39.16**. 

In my experiments, I find that the cache of the chrome dev may load the the opencv.js tested before. For example, I test the simd version firstly. Then when I try to test the wasm version, the chrome dev may loaded the cache of simd version of opencv.js and give out the same results. I think the reason is that the `http-server` create simple server at the same ip address and port.

**Comment by huningxin** [comment] 2020-06-08 14:12
You can build opencv.js with different options (e.g. non-simd vs. simd) in different folders, then launch different instances of node.js http-server in each folder. The two http-servers will occupy different ports (e.g. 8080 and 8081).

To disable the chrome disk cache, you can open the developer tools, go to network tab and check "disable cache". 

![image](https://user-images.githubusercontent.com/1005673/84040278-024dc200-a9d5-11ea-8ff4-46d514047151.png)

**Comment by huningxin** [comment] 2020-06-12 05:20
With #341 merged, I built and ran the perf tests with emscripten 1.39.16 and chrome dev 85.0.4164.4. My CPU is i7-8665U @ 1.90GHz.

|  | WASM Scalar (mean time) |  WASM SIMD (mean time) | SIMD speedup |
|---|---|---|---|
| CvtColor (1920x1080,COLOR_RGBA2GRAY) | 2.88 | 3.38 | 0.85X |
| resize  (CV_8UC1,640x480,960x540) | 2.65 | 1.45 | 1.82X |
| threshold (1920x1080, CV_8UC1, THRESH_BINARY) | 1.31 | 0.19 | 6.8X  |

@lionkunonly 

The SIMD version of CvtColor kernel is still slower than scalar version according to my test.

Comparing to the last data in #284 and #301 , 
* cvtColor: scalar: 2.747 ms, simd: 11.355, SIMD sppedup is 0.24X.
* Resize: scalar: 5.319 ms, simd: 4.410 ms, SIMD speedup is 1.2X.

there are some improvements in latest emscripten and chrome v8.

**Comment by lionkunonly** [comment] 2020-06-12 05:55
It is a good test, but the result is different with what i got from my test.  I am going to retest it. Is the scalar version built with `--build_wasm` only?

**Comment by huningxin** [comment] 2020-06-12 06:14
> Is the scalar version built with `--build_wasm` only?

Yes.

**Comment by lionkunonly** [comment] 2020-06-12 06:31
@huningxin . The retest result is:
|  | WASM Scalar (mean time) |  WASM SIMD (mean time) | SIMD speedup |
|---|---|---|---|
| CvtColor (1920x1080,COLOR_RGBA2GRAY) | 8.0948 | 4.5518 | 1.778X |
| resize  (CV_8UC1,640x480,960x540) | 5.5866 | 1.9314 | 2.89X |
| threshold (1920x1080, CV_8UC1, THRESH_BINARY) | 4.6089 | 0.1596 | 25.49X  |


The SIMD can bring big improvement in my computer. But I find that the time cost of my WASM scalar version is very high. I think the bad performance of the WASM scalar version makes me think the SIMD can speed up the WASM Scalar version. So the issue maybe still here.

**Comment by huningxin** [comment] 2020-06-12 06:48
I tested on another machine with i7-8700 CPU @ 3.20GHz, the data I got:

|  | WASM Scalar (mean time) |  WASM SIMD (mean time) | SIMD speedup |
|---|---|---|---|
| CvtColor (1920x1080,COLOR_RGBA2GRAY) | 2.33 | 2.77 | 0.84X |
| resize  (CV_8UC1,640x480,960x540) | 2.17 | 1.25 | 1.73X |
| threshold (1920x1080, CV_8UC1, THRESH_BINARY) | 1.19 | 0.15 | 7.9X  |

**Closed as completed** 2020-07-06 07:03 UTC
Labels: simd

**Comment by huningxin** [comment] 2020-07-06 07:05
@lionkunonly , please post the perf test result of cvtColor to #301 and resize to #284 .
